language: csharp
before_install:
 - chmod +x build/build.mono.sh
install:
  - nuget restore JinianNet.JNTemplate.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - ./build/build.mono.sh
  - xbuild /p:Configuration=Release JinianNet.JNTemplate.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/JinianNet.JNTemplate.Test/bin/Release/JinianNet.JNTemplate.Test.dll