language: csharp
solution: MyGame.sln
install:
  - sudo apt-get install nunit-console
  - nuget restore MyGame.sln
script:
  - xbuild ./MyGame.sln
  - nunit-console ./UnitTestProject1/bin/Debug/UnitTestProject1.dll